volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/pg_data
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media

  frontend:
    env_file: .env
    build : ./frontend
    container_name: frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    build: ./nginx
    env_file: .env
    container_name: nginx
    depends_on:
      - backend
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 8000:80
  
networks:
  default:
    driver: bridge
    name: foodgram-network

