[tool.isort]
# Основные настройки
profile = "black"
line_length = 79

# Локальные Django-приложения  проекта
known_first_party = [
    "recipes",
    "users",
    "api",
    "foodgram" 
]

# Строгое разделение по PEP 8
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]

# Детальные настройки
force_sort_within_sections = true
lines_between_sections = 1
lines_after_imports = 2
combine_as_imports = true
multi_line_output = 3
include_trailing_comma = true
skip = [
    "migrations", 
    "env",         
    ".venv",
    "venv",
    "__pycache__"
]