# Generated by Django 5.1.6 on 2025-02-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_cooking_time_alter_recipe_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='fne5oj', unique=True),
        ),
    ]
