# Generated by Django 5.1.6 on 2025-02-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_rename_quantity_ingredientinrecipe_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='Z2OMAg', unique=True),
        ),
    ]
