# Generated by Django 5.1.6 on 2025-02-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='XpMLJJ0HE6ow2ZwsEQH0', max_length=200, unique=True),
        ),
    ]
