# Generated by Django 5.1.6 on 2025-02-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='ZnYOk5Q940trzF1M12fT', max_length=200, unique=True),
        ),
    ]
