# Generated by Django 5.1.6 on 2025-02-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='zWtcCl49WWcpgWZ8H5kb', max_length=200, unique=True),
        ),
    ]
