# Generated by Django 5.1.6 on 2025-02-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='a8Qg08cacWJYXCyeRSP9', max_length=200, unique=True),
        ),
    ]
