# Generated by Django 5.1.6 on 2025-02-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='e8543EbHcxcxd7kf0uub', max_length=200, unique=True),
        ),
    ]
