# Generated by Django 5.1.6 on 2025-02-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0033_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='2oNHMDXR4A7KkUFC53oy', max_length=200, unique=True),
        ),
    ]
