# Generated by Django 5.1.6 on 2025-02-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='bbyHb31AfLVz9r9LmJOt', max_length=200, unique=True),
        ),
    ]
