# Generated by Django 5.1.6 on 2025-02-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='Khnd7DLqRODY7kSvyVtS', max_length=200, unique=True),
        ),
    ]
