# Generated by Django 3.2 on 2025-03-29 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение 1!'), django.core.validators.MaxValueValidator(50000, message='Максимальное значение 100!')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение 1!'), django.core.validators.MaxValueValidator(1000000, message='Максимальное значение 300!')], verbose_name='Время приготовления'),
        ),
    ]
