# Generated by Django 5.1.6 on 2025-03-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='0GBW4rc7ysFR3KeWQcSx', max_length=20, unique=True),
        ),
    ]
