# Generated by Django 5.1.6 on 2025-03-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='6erHRNBJ1zKyM37FQIZi', max_length=20, unique=True),
        ),
    ]
