# Generated by Django 5.1.6 on 2025-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='uxPb910bRaof5aO4QOWo', max_length=20, unique=True),
        ),
    ]
