# Generated by Django 5.1.6 on 2025-02-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='30z4wn6Y2X6gRvm7RL4q', max_length=20, unique=True),
        ),
    ]
