# Generated by Django 3.2 on 2025-03-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='0vb8DAGkgUeQj6b841Nm', max_length=20, unique=True),
        ),
    ]
