# Generated by Django 5.1.6 on 2025-02-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredientinrecipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='WEmu5bZxWZTGwadUaLw0', max_length=20, unique=True),
        ),
    ]
