# Generated by Django 3.2 on 2025-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='emqOwkCAKQaJd4V4bloc', max_length=20, unique=True),
        ),
    ]
