# Generated by Django 5.1.6 on 2025-02-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='cBw8G2KJdxm21O6uUwNw', max_length=20, unique=True),
        ),
    ]
