# Generated by Django 5.1.6 on 2025-02-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='IvxnoOEcdV1AjhZ7OnF6', max_length=20, unique=True),
        ),
    ]
