# Generated by Django 3.2 on 2025-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='Q3WP4m7Nb7mKR3pHRez9', editable=False, max_length=20, unique=True),
        ),
    ]
