# Generated by Django 5.1.6 on 2025-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='HMQxR3mM0d6f1Zo29VH4', max_length=20, unique=True),
        ),
    ]
