# Generated by Django 5.1.6 on 2025-02-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='iAnEKpkeHtvU5c2BYusb', max_length=20, unique=True),
        ),
    ]
