# Generated by Django 5.1.6 on 2025-02-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='BeaF0fp6YrG9MkVEHEuU', max_length=20, unique=True),
        ),
    ]
