# Generated by Django 5.1.6 on 2025-02-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('author', 'user'), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
